[project]
name = "agent-latest-news"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk[http-server]>=0.3.10",
    "mcp>=1.18.0",
    "uvicorn>=0.38.0",
]
